#!/usr/bin/env bash
# Generated by installr for installr.
# https://github.com/jasenmichael/installr
set -euo pipefail

APP_NAME='installr'
APP_VERSION='0.1.0'
HAS_VERSION=yes
SCOPE_LOCK=''
if [[ -n $SCOPE_LOCK ]]; then
  SCOPE=$SCOPE_LOCK
else
  SCOPE=local
fi
ASSUME_YES=no
while [[ $# -gt 0 ]]; do
  case $1 in
    -h | --help)
      cat <<EOF
$APP_NAME installer.

Usage: install.sh [options]

Options:
  -h, --help     Show this help and exit (before fetch).
  -v, --version  Print "$APP_NAME <version>" and exit (before fetch).
  --local        Install under the local prefix.
  --global       Install under the global prefix (sudo if not root).
  --yes          Replace an existing app config without prompting.

Scope lock: when the author set SCOPE=local, --global fails.
When SCOPE=global, --local fails. When SCOPE is omitted, default is local
and both --local and --global are allowed.
EOF
      exit 0
      ;;
    -v | --version)
      printf '%s %s\n' "$APP_NAME" "$APP_VERSION"
      exit 0
      ;;
    --local)
      if [[ $SCOPE_LOCK == global ]]; then
        printf 'install.sh: SCOPE is global; --local is not allowed\n' >&2
        exit 1
      fi
      SCOPE=local
      shift
      ;;
    --global)
      if [[ $SCOPE_LOCK == local ]]; then
        printf 'install.sh: SCOPE is local; --global is not allowed\n' >&2
        exit 1
      fi
      SCOPE=global
      shift
      ;;
    --yes) ASSUME_YES=yes; shift ;;
    *)
      printf 'install.sh: unknown argument: %s\n' "$1" >&2
      exit 2
      ;;
  esac
done
case "$(uname -s)" in
  Linux) OS=linux ;;
  Darwin) OS=darwin ;;
  *)
    printf 'install.sh: unknown os: %s\n' "$(uname -s)" >&2
    exit 1
    ;;
esac

case "$(uname -m)" in
  x86_64 | amd64) ARCH=amd64 ;;
  aarch64 | arm64) ARCH=arm64 ;;
  *)
    printf 'install.sh: unknown arch: %s\n' "$(uname -m)" >&2
    exit 1
    ;;
esac
LOCAL_PREFIX=${HOME}/.local
GLOBAL_PREFIX=/usr/local

if [[ $SCOPE == global ]]; then
  PREFIX=$GLOBAL_PREFIX
  APP_DIR=$PREFIX/$APP_NAME
  BIN_DIR=$PREFIX/bin
else
  PREFIX=$LOCAL_PREFIX
  APP_DIR=$PREFIX/share/$APP_NAME
  BIN_DIR=$PREFIX/bin
fi
USED_SUDO=no
if [[ $SCOPE == global && $(id -u) -ne 0 ]]; then
  USED_SUDO=yes
fi

as_root() {
  if [[ $USED_SUDO == yes ]]; then
    sudo "$@"
  else
    "$@"
  fi
}
command -v git >/dev/null 2>&1 || {
  printf 'install.sh: missing dep: git\n' >&2
  exit 1
}

FILES_MODE=none
REPO_URL='https://github.com/jasenmichael/installr.git'
REPO_REF='main'
if [[ $FILES_MODE == star ]]; then
  if [[ -d $APP_DIR/.git ]]; then
    as_root git -C "$APP_DIR" fetch --depth 1 origin "$REPO_REF"
    as_root git -C "$APP_DIR" checkout --force FETCH_HEAD
  elif [[ -e $APP_DIR ]]; then
    printf 'install.sh: APP_DIR exists and is not a git repo: %s\n' "$APP_DIR" >&2
    exit 1
  else
    as_root mkdir -p -- "$(dirname -- "$APP_DIR")"
    as_root git clone --depth 1 --branch "$REPO_REF" "$REPO_URL" "$APP_DIR"
  fi
  STAGE=$APP_DIR
else
  STAGE=$(mktemp -d)
  git clone --depth 1 --branch "$REPO_REF" "$REPO_URL" "$STAGE"
fi

BIN_PATTERN='bin/installr'
BIN_OVERRIDE=
case "${OS}_${ARCH}" in
  linux_amd64) BIN_OVERRIDE='' ;;
  linux_arm64) BIN_OVERRIDE='' ;;
  darwin_amd64) BIN_OVERRIDE='' ;;
  darwin_arm64) BIN_OVERRIDE='' ;;
  *)
    printf 'install.sh: no binary for %s-%s\n' "$OS" "$ARCH" >&2
    exit 1
    ;;
esac

if [[ -n $BIN_OVERRIDE ]]; then
  BIN_REL=$BIN_OVERRIDE
elif [[ -n $BIN_PATTERN ]]; then
  BIN_REL=$BIN_PATTERN
  BIN_REL=${BIN_REL//\{\{name\}\}/$APP_NAME}
  BIN_REL=${BIN_REL//\{\{os\}\}/$OS}
  BIN_REL=${BIN_REL//\{\{arch\}\}/$ARCH}
else
  printf 'install.sh: no binary path for %s-%s\n' "$OS" "$ARCH" >&2
  exit 1
fi

FETCHED_BIN=$STAGE/$BIN_REL
FILES_MODE=none
FILES_SPEC=''
if [[ $FILES_MODE == list ]]; then
  IFS=',' read -ra _files_items <<< "$FILES_SPEC"
  _files_rels=()
  for _files_raw in "${_files_items[@]}"; do
    item=${_files_raw#"${_files_raw%%[![:space:]]*}"}
    item=${item%"${item##*[![:space:]]}"}
    item=${item%/}
    if [[ $item == *'*'* || $item == *'?'* || $item == *'['* ]]; then
      _files_matches=()
      while IFS= read -r _files_match; do
        [[ -n $_files_match ]] || continue
        _files_matches+=("$_files_match")
      done < <(cd "$STAGE" && compgen -G "$item" || true)
      if [[ ${#_files_matches[@]} -eq 0 ]]; then
        printf 'install.sh: FILES missing: %s\n' "$item" >&2
        exit 1
      fi
      for _files_match in "${_files_matches[@]}"; do
        _files_rels+=("$_files_match")
      done
    else
      if [[ ! -e "$STAGE/$item" ]]; then
        printf 'install.sh: FILES missing: %s\n' "$item" >&2
        exit 1
      fi
      _files_rels+=("$item")
    fi
  done
  as_root mkdir -p -- "$APP_DIR"
  for rel in "${_files_rels[@]}"; do
    dest=$APP_DIR/$rel
    as_root mkdir -p -- "$(dirname -- "$dest")"
    if [[ -d $STAGE/$rel ]]; then
      as_root cp -a -- "$STAGE/$rel" "$APP_DIR/$(dirname -- "$rel")/"
    else
      as_root cp -a -- "$STAGE/$rel" "$dest"
    fi
  done
  FILES_SUMMARY=""
  for rel in "${_files_rels[@]}"; do
    if [[ -z $FILES_SUMMARY ]]; then
      FILES_SUMMARY=$rel
    else
      FILES_SUMMARY="$FILES_SUMMARY, $rel"
    fi
  done
fi
FILES_MODE=none
if [[ $FILES_MODE == star ]]; then
  as_root mkdir -p -- "$BIN_DIR"
  as_root chmod +x "$FETCHED_BIN"
  as_root ln -sfn -- "$FETCHED_BIN" "$BIN_DIR/$APP_NAME"
  INSTALLED_BIN=$FETCHED_BIN
  FILES_SUMMARY='*'
else
  as_root mkdir -p -- "$APP_DIR" "$BIN_DIR"
  as_root cp -- "$FETCHED_BIN" "$APP_DIR/$APP_NAME"
  as_root chmod +x "$APP_DIR/$APP_NAME"
  as_root ln -sfn -- "$APP_DIR/$APP_NAME" "$BIN_DIR/$APP_NAME"
  INSTALLED_BIN=$APP_DIR/$APP_NAME
  if [[ $FILES_MODE != list ]]; then
    FILES_SUMMARY=binary
  fi
fi
DEFAULT_CONFIG=''
DEFAULT_CONFIG_BODY=''
CONFIG_EXT='toml'
CONFIG_INSTALLED=no
CONFIG_DEST=
CONFIG_ACTION=skipped
if [[ -n $DEFAULT_CONFIG || -n $DEFAULT_CONFIG_BODY ]]; then
  CONFIG_DEST=$HOME/.config/$APP_NAME.$CONFIG_EXT
  replace=no
  existed=no
  if [[ -e $CONFIG_DEST ]]; then
    existed=yes
  fi
  if [[ $existed == no ]]; then
    replace=yes
  elif [[ $ASSUME_YES == yes ]]; then
    replace=yes
  else
    read -r -p "Replace $CONFIG_DEST? [y/N] " ans || true
    if [[ ${ans:-} == y || ${ans:-} == Y || ${ans:-} == yes ]]; then
      replace=yes
    fi
  fi
  if [[ $replace == yes ]]; then
    mkdir -p -- "$(dirname -- "$CONFIG_DEST")"
    if [[ -n $DEFAULT_CONFIG_BODY ]]; then
      printf '%s\n' "$DEFAULT_CONFIG_BODY" > "$CONFIG_DEST"
    else
      cp -- "$STAGE/$DEFAULT_CONFIG" "$CONFIG_DEST"
    fi
    CONFIG_INSTALLED=yes
    if [[ $existed == yes ]]; then
      CONFIG_ACTION=replaced
    else
      CONFIG_ACTION=copied
    fi
  else
    CONFIG_ACTION=left
  fi
fi
CONFIG_DEST=${CONFIG_DEST:-}
CONFIG_INSTALLED=${CONFIG_INSTALLED:-no}
CONFIG_ACTION=${CONFIG_ACTION:-skipped}
USED_SUDO=${USED_SUDO:-no}

write_root() {
  local dest=$1
  if [[ $USED_SUDO == yes ]]; then
    sudo tee "$dest" >/dev/null
  else
    cat > "$dest"
  fi
}

write_root "$APP_DIR/install.log" <<EOF
APP_NAME=$APP_NAME
APP_DIR=$APP_DIR
BIN=$INSTALLED_BIN
SYMLINK=$BIN_DIR/$APP_NAME
CONFIG=$CONFIG_DEST
CONFIG_INSTALLED=$CONFIG_INSTALLED
SUDO=$USED_SUDO
EOF

write_root "$APP_DIR/uninstall.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
LOG=$HERE/install.log
if [[ ! -f $LOG ]]; then
  printf 'uninstall: missing install.log\n' >&2
  exit 1
fi

log_get() {
  local key=$1 line k v
  while IFS= read -r line || [[ -n $line ]]; do
    [[ -z $line || $line == \#* ]] && continue
    k=${line%%=*}
    v=${line#*=}
    if [[ $k == "$key" ]]; then
      printf '%s' "$v"
      return 0
    fi
  done < "$LOG"
  return 1
}

APP_DIR=$(log_get APP_DIR || true)
if [[ -z ${APP_DIR:-} || $APP_DIR != "$HERE" ]]; then
  printf 'uninstall: APP_DIR mismatch\n' >&2
  exit 1
fi
if [[ $APP_DIR == / || $APP_DIR == "${HOME:-}" ]]; then
  printf 'uninstall: refusing %s\n' "$APP_DIR" >&2
  exit 1
fi

SUDO_NEEDED=$(log_get SUDO || true)
SYMLINK=$(log_get SYMLINK || true)
CONFIG=$(log_get CONFIG || true)
CONFIG_INSTALLED=$(log_get CONFIG_INSTALLED || true)

run_rm() {
  if [[ ${SUDO_NEEDED:-} == yes ]]; then
    sudo rm -rf -- "$@"
  else
    rm -rf -- "$@"
  fi
}

if [[ -n ${SYMLINK:-} ]]; then
  run_rm "$SYMLINK"
fi
if [[ ${CONFIG_INSTALLED:-} == yes && -n ${CONFIG:-} ]]; then
  run_rm "$CONFIG"
fi
run_rm "$APP_DIR"
EOF
as_root chmod +x "$APP_DIR/uninstall.sh"

if [[ ${HAS_VERSION:-no} == yes ]]; then
  printf 'version: %s\n' "$APP_VERSION"
fi
printf 'installed: %s\n' "$APP_DIR"
printf 'symlink: %s\n' "$BIN_DIR/$APP_NAME"
printf 'files: %s\n' "$FILES_SUMMARY"
case ${CONFIG_ACTION:-skipped} in
  copied) printf 'config: copied %s\n' "$CONFIG_DEST" ;;
  replaced) printf 'config: replaced %s\n' "$CONFIG_DEST" ;;
  left) printf 'config: left in place %s\n' "$CONFIG_DEST" ;;
  *) printf 'config: skipped (no DEFAULT_CONFIG)\n' ;;
esac
if [[ $USED_SUDO == yes ]]; then
  printf 'scope: %s (sudo)\n' "$SCOPE"
else
  printf 'scope: %s\n' "$SCOPE"
fi
case :$PATH: in
  *:"$BIN_DIR":*) ;;
  *) printf 'export PATH="%s:$PATH"\n' "$BIN_DIR" ;;
esac
