#!/usr/bin/env bats

bats_require_minimum_version 1.5.0

setup() {
  REPO_ROOT=$(cd "$BATS_TEST_DIRNAME/.." && pwd)
  INSTALLR="$REPO_ROOT/src/installr.sh"
  WORK=$(mktemp -d)
  cd "$WORK"
}

teardown() {
  rm -rf "$WORK"
}

@test "missing APP_NAME exits 1 and names the field" {
  printf 'SOURCE=github_release\n' > installr.conf
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 1 ]
  [[ "$stderr" == *"APP_NAME"* ]]
}

@test "release config emits header, os and arch detection, and the asset URL" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=github_release
GH_ASSET_URL=https://github.com/acme/myapp/releases/latest/download/{{name}}-{{os}}-{{arch}}
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 0 ]
  [ -f install.sh ]
  [ "$(head -n 1 install.sh)" = '#!/usr/bin/env bash' ]
  grep -q 'set -euo pipefail' install.sh
  grep -F -q 'https://github.com/jasenmichael/installr' install.sh
  grep -q 'Generated by installr' install.sh
  [[ "$output" == *"wrote install.sh"* ]]
  grep -q 'uname -s' install.sh
  grep -q 'Darwin' install.sh
  grep -q 'linux' install.sh
  grep -q 'uname -m' install.sh
  grep -q 'amd64' install.sh
  grep -q 'arm64' install.sh
  grep -F -q 'https://github.com/acme/myapp/releases/latest/download/{{name}}-{{os}}-{{arch}}' install.sh
  grep -q 'curl' install.sh
}

@test "INSTALL_SCRIPT selects the output path" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=github_release
GH_ASSET_URL=https://github.com/acme/myapp/releases/latest/download/{{name}}-{{os}}-{{arch}}
INSTALL_SCRIPT=custom.sh
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 0 ]
  [ -f custom.sh ]
  [ ! -e install.sh ]
}

@test "INSTALLR_OUTPUT overrides INSTALL_SCRIPT" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=github_release
GH_ASSET_URL=https://github.com/acme/myapp/releases/latest/download/{{name}}-{{os}}-{{arch}}
INSTALL_SCRIPT=from-file.sh
EOF
  run --separate-stderr env INSTALLR_OUTPUT=from-env.sh "$INSTALLR"
  [ "$status" -eq 0 ]
  [ -f from-env.sh ]
  [ ! -e from-file.sh ]
}

@test "--output overrides INSTALLR_OUTPUT" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=github_release
GH_ASSET_URL=https://github.com/acme/myapp/releases/latest/download/{{name}}-{{os}}-{{arch}}
INSTALL_SCRIPT=from-file.sh
EOF
  run --separate-stderr env INSTALLR_OUTPUT=from-env.sh "$INSTALLR" --output from-flag.sh
  [ "$status" -eq 0 ]
  [ -f from-flag.sh ]
  [ ! -e from-env.sh ]
  [ ! -e from-file.sh ]
}

@test "--config overrides INSTALLR_CONFIG" {
  cat > from-env.conf <<'EOF'
APP_NAME=from-env
SOURCE=github_release
GH_ASSET_URL=https://example.com/env
EOF
  cat > from-flag.conf <<'EOF'
APP_NAME=from-flag
SOURCE=github_release
GH_ASSET_URL=https://example.com/flag-asset
EOF
  run --separate-stderr env INSTALLR_CONFIG=from-env.conf "$INSTALLR" --config from-flag.conf
  [ "$status" -eq 0 ]
  grep -q 'from-flag' install.sh
  grep -F -q 'https://example.com/flag-asset' install.sh
  ! grep -q 'from-env' install.sh
}

@test "--check exits 0 and writes nothing" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=github_release
GH_ASSET_URL=https://github.com/acme/myapp/releases/latest/download/{{name}}-{{os}}-{{arch}}
EOF
  run --separate-stderr "$INSTALLR" --check
  [ "$status" -eq 0 ]
  [ ! -e install.sh ]
  [ -z "$output" ]
}

@test "repo config emits git clone and omits the release download" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=repo
REPO_URL=https://github.com/acme/myapp.git
BIN=dist/{{name}}
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 0 ]
  grep -q 'git clone' install.sh
  grep -F -q 'https://github.com/acme/myapp.git' install.sh
  ! grep -q 'curl -fsSL' install.sh
}

@test "BIN pattern with placeholders is baked into install.sh" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=repo
REPO_URL=https://github.com/acme/myapp.git
BIN=dist/{{name}}-{{os}}-{{arch}}
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 0 ]
  grep -F -q 'dist/{{name}}-{{os}}-{{arch}}' install.sh
  ! grep -q 'BIN_linux_amd64' install.sh
}

@test "BIN_* override wins over BIN for that platform" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=repo
REPO_URL=https://github.com/acme/myapp.git
BIN=dist/{{name}}-{{os}}-{{arch}}
BIN_darwin_arm64=out/apple-silicon
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 0 ]
  grep -F -q 'dist/{{name}}-{{os}}-{{arch}}' install.sh
  grep -F -q 'out/apple-silicon' install.sh
}

@test "repo with neither BIN nor BIN_* fails and names BIN" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=repo
REPO_URL=https://github.com/acme/myapp.git
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 1 ]
  [[ "$stderr" == *"BIN"* ]]
}

@test "BIN_* alone without BIN is valid" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=repo
REPO_URL=https://github.com/acme/myapp.git
BIN_linux_amd64=dist/linux-only
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 0 ]
  grep -F -q 'dist/linux-only' install.sh
}

@test "BUILD is baked into the repo install.sh" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=repo
REPO_URL=https://github.com/acme/myapp.git
BUILD=make build-dummy
BIN=dist/{{name}}
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 0 ]
  grep -F -q 'make build-dummy' install.sh
}

@test "empty BUILD omits the build command" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=repo
REPO_URL=https://github.com/acme/myapp.git
BIN=dist/{{name}}
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 0 ]
  ! grep -q 'build-dummy' install.sh
  ! grep -q 'bash -lc' install.sh
}

@test "release install.sh does not clone" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=github_release
GH_ASSET_URL=https://github.com/acme/myapp/releases/latest/download/{{name}}-{{os}}-{{arch}}
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 0 ]
  ! grep -q 'git clone' install.sh
}

@test "empty DEPS omits the dep loop" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=github_release
GH_ASSET_URL=https://github.com/acme/myapp/releases/latest/download/{{name}}-{{os}}-{{arch}}
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 0 ]
  ! grep -q 'for dep in' install.sh
}

@test "DEPS are checked in install.sh" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=github_release
GH_ASSET_URL=https://github.com/acme/myapp/releases/latest/download/{{name}}-{{os}}-{{arch}}
DEPS=make jq
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 0 ]
  grep -F -q 'for dep in make jq; do' install.sh
}

@test "bad SOURCE exits 1 and names the field" {
  printf 'APP_NAME=dummy\nSOURCE=nope\n' > installr.conf
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 1 ]
  [[ "$stderr" == *"SOURCE"* ]]
}

@test "bad SCOPE exits 1 and names the field" {
  cat > installr.conf <<'EOF'
APP_NAME=dummy
SOURCE=github_release
GH_ASSET_URL=https://example.com/x
SCOPE=both
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 1 ]
  [[ "$stderr" == *"SCOPE"* ]]
}

@test "example config passes --check" {
  run --separate-stderr "$INSTALLR" --check --config "$REPO_ROOT/installr.conf.example"
  [ "$status" -eq 0 ]
}

@test "--help exits 0, lists config keys and README, writes nothing" {
  run --separate-stderr "$INSTALLR" --help
  [ "$status" -eq 0 ]
  [ ! -e install.sh ]
  [[ "$output" == *"APP_NAME"* ]]
  [[ "$output" == *"SOURCE"* ]]
  [[ "$output" == *"INSTALL_SCRIPT"* ]]
  [[ "$output" == *"SCOPE"* ]]
  [[ "$output" == *"LOCAL_PREFIX"* ]]
  [[ "$output" == *"GLOBAL_PREFIX"* ]]
  [[ "$output" == *"DEFAULT_CONFIG"* ]]
  [[ "$output" == *"CONFIG_EXT"* ]]
  [[ "$output" == *"CONFIG_PATH"* ]]
  [[ "$output" == *"DEPS"* ]]
  [[ "$output" == *"REPO_URL"* ]]
  [[ "$output" == *"REPO_REF"* ]]
  [[ "$output" == *"BUILD"* ]]
  [[ "$output" == *"BIN"* ]]
  [[ "$output" == *"BIN_linux_amd64"* ]]
  [[ "$output" == *"BIN_linux_arm64"* ]]
  [[ "$output" == *"BIN_darwin_amd64"* ]]
  [[ "$output" == *"BIN_darwin_arm64"* ]]
  [[ "$output" == *"GH_ASSET_URL"* ]]
  [[ "$output" == *"GH_VERSION"* ]]
  [[ "$output" == *"GH_EXT"* ]]
  [[ "$output" == *"GH_REPO"* ]]
  [[ "$output" == *"GH_ARCHIVE"* ]]
  [[ "$output" == *"GH_BIN_PATH"* ]]
  [[ "$output" == *"GH_BIN_PATH_linux_amd64"* ]]
  [[ "$output" == *"GH_BIN_PATH_linux_arm64"* ]]
  [[ "$output" == *"GH_BIN_PATH_darwin_amd64"* ]]
  [[ "$output" == *"GH_BIN_PATH_darwin_arm64"* ]]
  [[ "$output" == *"VERSION"* ]]
  [[ "$output" == *"README.md"* || "$output" == *"github.com/jasenmichael/installr"* ]]
}

@test "-h does not require a config file" {
  run --separate-stderr "$INSTALLR" -h
  [ "$status" -eq 0 ]
  [ ! -e install.sh ]
}

@test "--version prints installr 0.1.0" {
  run --separate-stderr "$INSTALLR" --version
  [ "$status" -eq 0 ]
  [ "$output" = "installr 0.1.0" ]
  [ ! -e install.sh ]
}

@test "-v prints installr 0.1.0 without config" {
  run --separate-stderr "$INSTALLR" -v
  [ "$status" -eq 0 ]
  [ "$output" = "installr 0.1.0" ]
}

@test "VERSION literal bakes into install.sh --version" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=github_release
GH_ASSET_URL=https://example.com/{{name}}
VERSION=1.2.3
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 0 ]
  [[ "$output" == *"wrote install.sh"* ]]
  run --separate-stderr ./install.sh --version
  [ "$status" -eq 0 ]
  [ "$output" = "myapp 1.2.3" ]
  ! grep -q 'curl' <<<"$output"
  ! grep -q 'installed:' <<<"$output"
}

@test "VERSION=!cat VERSION resolves at generate time" {
  printf '9.9.9\n' > VERSION
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=github_release
GH_ASSET_URL=https://example.com/{{name}}
VERSION=!cat VERSION
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 0 ]
  run --separate-stderr ./install.sh -v
  [ "$status" -eq 0 ]
  [ "$output" = "myapp 9.9.9" ]
}

@test "VERSION=!false exits 1 and names VERSION" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=github_release
GH_ASSET_URL=https://example.com/x
VERSION=!false
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 1 ]
  [[ "$stderr" == *"VERSION"* ]]
  [ ! -e install.sh ]
}

@test "VERSION command with empty stdout exits 1 and names VERSION" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=github_release
GH_ASSET_URL=https://example.com/x
VERSION=!true
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 1 ]
  [[ "$stderr" == *"VERSION"* ]]
}

@test "no VERSION makes install.sh --version print unknown" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=github_release
GH_ASSET_URL=https://example.com/{{name}}
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 0 ]
  run --separate-stderr ./install.sh --version
  [ "$status" -eq 0 ]
  [ "$output" = "myapp unknown" ]
}

@test "{{version}} uses resolved VERSION over GH_VERSION" {
  cat > installr.conf <<'EOF'
APP_NAME=myapp
SOURCE=github_release
GH_ASSET_URL=https://example.com/releases/download/{{version}}/{{name}}
GH_VERSION=v0.0.1
VERSION=2.0.0
EOF
  run --separate-stderr "$INSTALLR"
  [ "$status" -eq 0 ]
  grep -F -q "GH_VERSION='2.0.0'" install.sh
  ! grep -F -q "GH_VERSION='v0.0.1'" install.sh
  grep -F -q 'releases/download/{{version}}' install.sh
}
